# First remove *all* keybindings
# unbind-key -a
# Now reinsert all the regular tmux keys
bind M-l lock-server
bind ^C new-window -c "$HOME"
bind ^D detach
bind * list-clients

bind-key X confirm-before -p "Kill this tmux session? (y/n)" kill-session
# bind-key -n C-x kill-session # -n means no prefix
bind-key C-x kill-session

bind H previous-window
bind L next-window

bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind z resize-pane -Z
bind ^L refresh-client
bind l refresh-client
bind | split-window
bind V split-window -v -c "#{pane_current_path}"
bind H split-window -h -c "#{pane_current_path}"
bind '"' choose-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
bind : command-prompt
bind * setw synchronize-panes
bind P set pane-border-status
bind ^q kill-pane
bind x swap-pane -D
bind S choose-session
bind R source-file ~/.config/tmux/tmux.conf
bind K send-keys "clear"\; send-keys "Enter"
bind-key -T copy-mode-vi v send-keys -X begin-selection

# In copy-mode-vi: y = copy but stay in copy mode
bind-key -T copy-mode-vi y send-keys -X copy-selection

# Copy current line, stay in copy-mode
bind-key -T copy-mode-vi Y send-keys -X copy-line

